// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc7280.mecanum_drive_test.subsystems;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.NeutralMode;
import com.ctre.phoenix.motorcontrol.can.VictorSPX;
import org.usfirst.frc7280.mecanum_drive_test.Constants;
import org.usfirst.frc7280.mecanum_drive_test.RobotMap;
import org.usfirst.frc7280.mecanum_drive_test.commands.SolenoidActivate;

import edu.wpi.first.wpilibj.command.Subsystem;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Solenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Intaker extends Subsystem {

    private VictorSPX intakerMotor = new VictorSPX(RobotMap.intakerMotor);

    Solenoid intakerSolenoid = new Solenoid(RobotMap.intakerSolenoid);


    public Intaker() {
        intakerMotor.setNeutralMode(NeutralMode.Brake);
        
    }

    @Override
    public void initDefaultCommand() {
         // setDefaultCommand(new SolenoidActivate());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    public void take(double _motorSpeed){
        intakerMotor.set(ControlMode.PercentOutput, _motorSpeed);
    }

    public void cylinderUp(){
        intakerSolenoid.set(true);        
    }

    public void cylinderDown(){
        intakerSolenoid.set(false);
    }
}

